= SSR Site Hosting
:!toc-title:
:!toc-placement:
:toc:


Creates the necessary infrastructure for hosting a Server-Side Rendered (SSR) frontend application on AWS using CloudFront.

This includes the provisioning of a S3 bucket for static files, an ACM certificate and a CloudFront distribution,
as well as Route 53 records

toc::[]

== Usage
Remember to check out the link:variables.tf[*variables*] and link:outputs.tf[*outputs*] to see all options.

[source, hcl]
----
module "ssr" {
  source = "github.com/nsbno/terraform-aws-ssr-site?ref=x.y.z"

  providers = {
    aws.us_east_1 = aws.us_east_1
  }

  service_name     = "infrademo-demo-app"
  domain_name      = "petstore.infrademo.vydev.io"
  alb_domain_name  = "lb.infrademo.vydev.io"

  route53_hosted_zone_id = module.metadata.dns.hosted_zone_id

  # Default is to create a new bucket, if you already have a bucket, use this instead
  # external_s3_bucket_id = aws_s3_bucket.existing.id # Uncomment this line to use an existing bucket
}
----
== Examples
- link:examples/complete/main.tf[Complete example] to see how to use this module
- link:examples/preview/main.tf[Preview example] to see how to be able to generate preview URLs for pull requests

== Relevant Repositories

You can use these repos together with this repo!

link:https://github.com/nsbno/terraform-aws-account-metadata[`nsbno/terraform-aws-account-metadata`]::
Contains metadata about your account, e.g. hosted zone ID to be used with this repo

link:https://github.com/nsbno/terraform-aws-ecs-service[`nsbno/terraform-aws-ecs-service`]::
Use this module to deploy an ECS service, for example your SSR server

link:https://github.com/nsbno/terraform-aws-multi-domain-static-site[`nsbno/terraform-aws-multi-domain-static-site`]::
Looking to deploy a static website (SPA) like a React app? Use this module

== CloudFront Origin Access Control (OAC)

If you want to restrict access to your S3 bucket so only CloudFront can read objects, use the CloudFront Origin Access Control (OAC) Principal ARN in your S3 bucket policy:

[source, hcl]
----
Principal = {
  "AWS": module.ssr.oac_principal_arn
}
----

Refer to the output `oac_principal_arn` for the correct value. The OAC resource is created and managed by the SSR module, and its ARN should be used in your S3 bucket policy for secure access

